# Generated by Django 5.2.5 on 2025-08-15 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_logalocacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria RTI')),
            ],
            options={
                'verbose_name_plural': 'Categorias RTI',
            },
        ),
        migrations.CreateModel(
            name='Dano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
            },
        ),
        migrations.CreateModel(
            name='Revestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('defeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas', to='spie.defeito')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_dano', models.FloatField(default=0, verbose_name='Extensão do Dano (%)')),
                ('complemento', models.TextField(blank=True, null=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.acesso')),
                ('dano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.dano')),
                ('revestimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.revestimento')),
                ('tipo_objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.tipoobjeto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='inspecao_imagens/')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='spie.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Equipamento')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_equipamento', to='core.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='TagEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='TAG do Equipamento')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='spie.tipoequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_zr', models.CharField(max_length=8, unique=True, verbose_name='Nota ZR')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria_rti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.categoriarti', verbose_name='Categoria RTI')),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.causa')),
                ('defeito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.defeito')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plataforma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to=settings.AUTH_USER_MODEL, verbose_name='Inspetor')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.modulo')),
                ('objetos', models.ManyToManyField(related_name='inspecoes', to='spie.objeto')),
                ('recomendacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.recomendacao', verbose_name='Recomendação')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.setor')),
                ('tag_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.tagequipamento', verbose_name='TAG do Equipamento')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spie.tipoequipamento', verbose_name='Tipo de Equipamento')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
