# Generated by Django 5.2.5 on 2025-08-14 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('Criação', 'Criação'), ('Atualização', 'Atualização'), ('Remoção', 'Remoção')], max_length=20)),
                ('detalhes', models.TextField(help_text='Detalhes da alocação no momento da ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alocacao', models.ForeignKey(help_text='Alocação que foi modificada', on_delete=django.db.models.deletion.CASCADE, to='core.alocacao')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
